apiVersion: v1
kind: Pod
metadata:
  name: technitium
  labels:
    app: technitium
spec:
  hostNetwork: true
  containers:
    - name: technitium
      image: technitium/dns-server:latest
      env:
        - name: TZ
          value: "America/New_York"
        - name: DNS_SERVER_DOMAIN
          value: "dns.home"
        - name: DNS_SERVER_PREFER_IPv6
          value: "false"
        - name: DNS_SERVER_WEB_SERVICE_HTTP_PORT
          value: "5380"
        - name: DNS_SERVER_RECURSION
          value: "Allow"
        - name: DNS_SERVER_LOG_USING_LOCAL_TIME
          value: "true"
      envFrom:
        - secretRef:
            name: app-secrets
      volumeMounts:
        - mountPath: /etc/dns
          name: technitium-data
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_BIND_SERVICE
  volumes:
    - name: technitium-data
      hostPath:
        path: ${PERSISTANT_PATH}/technitium/data
        type: DirectoryOrCreate