apiVersion: v1
kind: Pod
metadata:
  name: navidrome
spec:
  restartPolicy: Always
  containers:
    - name: navidrome
      image: docker.io/deluan/navidrome:latest
      env:
      - name: ND_AUTHREQUESTLIMIT
        value: "0"
      - name: ND_REVERSEPROXYWHITELIST
        value: "0.0.0.0/0"
      - name: ND_REVERSEPROXYUSERHEADER
        value: "X-Remote-User"
      envFrom:
        - secretRef:
            name: app-secrets
      ports:
        - containerPort: 4533
          hostPort: 9200
      volumeMounts:
        - name: data
          mountPath: /data
        - name: music
          mountPath: /music
          readOnly: true
        - name: tmp
          mountPath: /tmp
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "1000m"

  volumes:
    - name: data
      hostPath:
        path: ${PERSISTENT_PATH}/navidrome/data
        type: DirectoryOrCreate
    - name: music
      hostPath:
        path: ${PERSISTENT_PATH}/navidrome/music
        type: DirectoryOrCreate
    - name: tmp
      emptyDir: {}
