apiVersion: v1
kind: ServiceAccount
metadata:
  name: dozzle
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dozzle
subjects:
  - kind: ServiceAccount
    name: dozzle
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: dozzle
spec:
  serviceAccountName: dozzle
  containers:
    - name: dozzle
      image: amir20/dozzle:latest
      imagePullPolicy: IfNotPresent
      args:
        - --mode=server
      ports:
        - containerPort: 8080
          hostPort: 8095
      env:
        - name: DOZZLE_LEVEL
          value: "info"
        - name: DOZZLE_TAILSIZE
          value: "300"
        - name: DOZZLE_MODE
          value: "server"