apiVersion: v1
kind: Pod
metadata:
  name: ntfy
  labels:
    app: ntfy
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
    - name: ntfy
      image: docker.io/binwiederhier/ntfy:latest
      args: ["serve", "--listen-http", ":2586"]
      ports:
        - containerPort: 2586
          hostPort: 2586
      env:
        - name: TZ
          value: America/New_York
      volumeMounts:
        - mountPath: /var/cache/ntfy
          name: ntfy-cache
        - mountPath: /etc/ntfy
          name: ntfy-config
  volumes:
    - name: ntfy-cache
      hostPath:
        path: ${PERSISTANT_PATH}/ntfy/cache
        type: DirectoryOrCreate
    - name: ntfy-config
      hostPath:
        path: ${PERSISTANT_PATH}/ntfy/config
        type: DirectoryOrCreate