apiVersion: v1
kind: Pod
metadata:
  name: bentopdf
  labels:
    app: bentopdf
spec:
  restartPolicy: Always
  containers:
    - name: bentopdf
      image: docker.io/bentopdf/bentopdf:latest
      ports:
        - containerPort: 8080
          hostPort: 5500