---
apiVersion: v1
kind: Pod
metadata:
  name: freshrss
  labels:
    app: freshrss
spec:
  restartPolicy: Always
  containers:
    - name: freshrss
      image: docker.io/freshrss/freshrss:latest
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - -c
              - >-
                if [ -f /var/www/FreshRSS/data/config.php ]; then
                  sed -i -E "s/'host'\s*=>\s*'(lab\.home|host\.containers\.internal|postgres)'/'host' => '${POSTGRES_HOST}'/g" /var/www/FreshRSS/data/config.php;
                fi
      ports:
        - containerPort: 80
          hostPort: 9500
      env:
        - name: TZ
          value: "UTC"
        - name: CRON_MIN
          value: "*/20"
        - name: DB_TYPE
          value: "pgsql"
        - name: DB_HOST
          value: "${POSTGRES_HOST}"
        - name: DB_PORT
          value: "${POSTGRES_PORT}"
        - name: DB_NAME
          value: "freshrss"
        - name: DB_USER
          value: "${POSTGRES_USER}"
        - name: DB_PASSWORD
          value: "${POSTGRES_PASSWORD}"
      volumeMounts:
        - mountPath: /var/www/FreshRSS/data
          name: freshrss-data
        - mountPath: /var/www/FreshRSS/extensions
          name: freshrss-extensions
  volumes:
    - name: freshrss-data
      hostPath:
        path: ${PERSISTANT_PATH}/freshrss/data
        type: DirectoryOrCreate
    - name: freshrss-extensions
      hostPath:
        path: ${PERSISTANT_PATH}/freshrss/extensions
        type: DirectoryOrCreate
