apiVersion: v1
kind: Pod
metadata:
  name: memos
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
    - name: memos
      image: docker.io/neosmemo/memos:stable
      imagePullPolicy: IfNotPresent
      env:
        - name: MEMOS_PUBLIC
          value: "true"
        - name: MEMOS_MODE
          value: "prod"
        - name: MEMOS_DRIVER
          value: "postgres"
        - name: MEMOS_PORT
          value: "5400"
        - name: MEMOS_DSN
          value: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/memos?sslmode=disable"
      ports:
        - containerPort: 5400