apiVersion: v1
kind: Pod
metadata:
  name: memos
spec:
  restartPolicy: Always
  containers:
    - name: memos
      image: ghcr.io/usememos/memos:stable
      imagePullPolicy: IfNotPresent
      env:
        - name: MEMOS_PUBLIC
          value: "true"
        - name: MEMOS_MODE
          value: "prod"
        - name: MEMOS_DRIVER
          value: "postgres"
        - name: MEMOS_PORT
          value: "5400"
        - name: MEMOS_DSN
          value: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${HOST_IP}:5432/memos?sslmode=disable"
      ports:
        - containerPort: 5400
          hostPort: 5400
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  volumes:
    - name: tmp
      emptyDir: {}