apiVersion: v1
kind: ServiceAccount
metadata:
  name: dozzle
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dozzle
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dozzle
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dozzle
subjects:
  - kind: ServiceAccount
    name: dozzle
    namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: dozzle
spec:
  serviceAccountName: dozzle
  initContainers:
    - name: wait-for-api
      image: busybox:1.37.0
      command:
        - sh
        - -c
        - |
          until nc -z 10.43.0.1 443; do
            echo "Waiting for Kubernetes API...";
            sleep 2;
          done
  containers:
    - name: dozzle
      image: amir20/dozzle:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
          hostPort: 8095
      env:
        - name: DOZZLE_LEVEL
          value: "info"
        - name: DOZZLE_MODE
          value: "k8s"
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  volumes:
    - name: tmp
      emptyDir: {}