apiVersion: v1
kind: Pod
metadata:
  name: qdrant
  labels:
    app: qdrant
spec:
  restartPolicy: Always
  containers:
    - name: qdrant
      image: docker.io/qdrant/qdrant:v1.13.4
      ports:
        - containerPort: 6333
          hostPort: 6333
          name: http
        - containerPort: 6334
          hostPort: 6334
          name: grpc
      env:
        - name: QDRANT__SERVICE__HTTP_PORT
          value: "6333"
        - name: QDRANT__SERVICE__GRPC_PORT
          value: "6334"
        - name: QDRANT__STORAGE__STORAGE_PATH
          value: "/qdrant/storage"
        - name: QDRANT__TELEMETRY_DISABLED
          value: "true"
        - name: QDRANT__SERVICE__ENABLE_CORS
          value: "true"
      envFrom:
        - secretRef:
            name: app-secrets
      volumeMounts:
        - mountPath: /qdrant/storage
          name: qdrant-data
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "1000m"
  volumes:
    - name: qdrant-data
      hostPath:
        path: ${PERSISTANT_PATH}/qdrant
        type: DirectoryOrCreate