apiVersion: v1
kind: Pod
metadata:
  name: actualbudget
spec:
  restartPolicy: Always
  securityContext:
    seLinuxOptions:
      level: s0
      type: unconfined_t
  containers:
    - name: actualbudget
      image: docker.io/actualbudget/actual-server:latest
      ports:
        - containerPort: 5006
          hostPort: 5020
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"

  volumes:
    - name: data
      hostPath:
        path: ${PERSISTENT_PATH}/actualbudget
        type: DirectoryOrCreate
    - name: tmp
      emptyDir: {}
