apiVersion: v1
kind: Pod
metadata:
  name: duplicati
  labels:
    app: duplicati
spec:
  restartPolicy: Always
  containers:
    - name: duplicati
      image: lscr.io/linuxserver/duplicati:latest
      env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/New_York"
        - name: SETTINGS_ENCRYPTION_KEY
          value: "${DUPLICATI_SETTINGS_ENCRYPTION_KEY}"
        - name: CLI_ARGS
          value: "--webservice-password=${DUPLICATI_WEB_PASSWORD} --webservice-interface=any --webservice-allowed-hostnames=*"
      ports:
        - containerPort: 8200
          hostPort: 8200
          protocol: TCP
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "768Mi"
          cpu: "500m"
      volumeMounts:
        - name: config
          mountPath: /config
        - name: backups
          mountPath: /backups
        - name: onedrive-source
          mountPath: /onedrive
          readOnly: true
        - name: dropbox-source
          mountPath: /dropbox
          readOnly: true
        - name: source
          mountPath: /source
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: ${PERSISTENT_PATH}/duplicati/config
        type: DirectoryOrCreate
    - name: backups
      hostPath:
        path: ${PERSISTENT_PATH}/duplicati/backups
        type: DirectoryOrCreate
    - name: onedrive-source
      hostPath:
        path: /home/admin/onedrive
        type: Directory
    - name: dropbox-source
      hostPath:
        path: /srv/dockerdata
        type: Directory
    - name: source
      hostPath:
        path: ${PERSISTENT_PATH}
        type: Directory
    - name: localtime
      hostPath:
        path: /etc/localtime
        type: File
